In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("LeakMind environment is working!")

Matplotlib is building the font cache; this may take a moment.

Pandas: 3.0.6
NumPy: 2.5.3
LeakMind environment is working!

In [2]:
import sys
print(sys.executable)

c:\Users\USER\OneDrive\Desktop\leakmind project\.venv\Scripts\python.exe

In [3]:
import pandas as pd
print(pd.__version__)

ModuleNotFoundError: No module named 'pandas'

In [4]:
import sys
print(sys.executable)

c:\Users\USER\OneDrive\Desktop\leakmind project\.venv\Scripts\python.exe

In [6]:
import os

raw_path = "../data/raw"

files = os.listdir(raw_path)

print("Files inside data/raw:")
for file in files:
    print(file)

Files inside data/raw:
r1

In [7]:
for file in files:
    path = os.path.join(raw_path, file)
    print(file, "->", os.path.getsize(path) / (1024 * 1024), "MB")

r1 -> 0.0 MB

In [8]:
import os

r1_path = "../data/raw/r1"

for root, dirs, files in os.walk(r1_path):
    print("\nFolder:", root)

    for file in files:
        print("  File:", file)

Folder: ../data/raw/r1

Folder: ../data/raw/r1\r1
  File: device.csv
  File: http.csv
  File: license.txt
  File: logon.csv
  File: readme.txt

Folder: ../data/raw/r1\r1\LDAP
  File: 2009-12.csv
  File: 2010-01.csv
  File: 2010-02.csv
  File: 2010-03.csv
  File: 2010-04.csv
  File: 2010-05.csv
  File: 2010-06.csv
  File: 2010-07.csv
  File: 2010-08.csv
  File: 2010-09.csv
  File: 2010-10.csv
  File: 2010-11.csv
  File: 2010-12.csv
  File: 2011-01.csv
  File: 2011-02.csv
  File: 2011-03.csv
  File: 2011-04.csv
  File: 2011-05.csv

In [9]:
import pandas as pd

logon_path = "../data/raw/r1/r1/logon.csv"

logon = pd.read_csv(logon_path)

print("Logon shape:", logon.shape)
print("\nColumns:")
print(logon.columns.tolist())

print("\nFirst 5 rows:")
display(logon.head())

Logon shape: (849579, 5)

Columns:
['id', 'date', 'user', 'pc', 'activity']

First 5 rows:

,id,date,user,pc,activity
0,{Y6O4-A7KC67IN-0899AOZK},01/04/2010 00:10:37,DTAA/KEE0997,PC-1914,Logon
1,{O5Y6-O7CJ02JC-6704RWBS},01/04/2010 00:52:16,DTAA/KEE0997,PC-1914,Logoff
2,{D2D1-C6EB14QJ-2100RSZO},01/04/2010 01:17:20,DTAA/KEE0997,PC-3363,Logon
3,{H9W1-X0MC70BT-6065RPAT},01/04/2010 01:28:34,DTAA/KEE0997,PC-3363,Logoff
4,{H3H4-S5AZ00AZ-9560IYHC},01/04/2010 01:57:30,DTAA/BJM0992,PC-3058,Logon

In [10]:
print("Activity values:")
print(logon["activity"].value_counts())

print("\nNumber of users:")
print(logon["user"].nunique())

print("\nNumber of PCs:")
print(logon["pc"].nunique())

print("\nDate range:")
print(logon["date"].min(), "to", logon["date"].max())

Activity values:
activity
Logon     470877
Logoff    378702
Name: count, dtype: int64

Number of users:
1000

Number of PCs:
1100

Date range:
01/03/2011 00:22:06 to 12/31/2010 06:58:51

In [11]:
logon["date"] = pd.to_datetime(
    logon["date"],
    format="%m/%d/%Y %H:%M:%S"
)

print("Correct date range:")
print(logon["date"].min())
print("to")
print(logon["date"].max())

Correct date range:
2010-01-04 00:10:37
to
2011-05-14 06:18:12

In [12]:
print("Missing values:")
print(logon.isnull().sum())

print("\nDuplicate rows:")
print(logon.duplicated().sum())

Missing values:
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

Duplicate rows:
0

In [13]:
print("\nData types:")
print(logon.dtypes)

Data types:
id                     str
date        datetime64[us]
user                   str
pc                     str
activity               str
dtype: object

In [14]:
device = pd.read_csv("../data/raw/r1/r1/device.csv")

print("Device shape:", device.shape)

print("\nColumns:")
print(device.columns.tolist())

print("\nFirst 5 rows:")
display(device.head())

Device shape: (65668, 5)

Columns:
['id', 'date', 'user', 'pc', 'activity']

First 5 rows:

,id,date,user,pc,activity
0,{S7A7-Y8QZ65MW-8738SAZP},01/04/2010 07:12:31,DTAA/RES0962,PC-3736,Connect
1,{G7A8-G1OB94NR-3006NTXH},01/04/2010 07:35:40,DTAA/BJC0569,PC-2588,Connect
2,{R3L8-N0LW95FR-8358LLXS},01/04/2010 08:00:38,DTAA/EMZ0196,PC-1479,Connect
3,{I2F1-B5FB51FL-3128HBUL},01/04/2010 08:02:14,DTAA/ZKH0388,PC-1021,Connect
4,{P7R6-C5TV18CT-1677DWWM},01/04/2010 08:20:17,DTAA/RES0962,PC-3736,Disconnect

In [15]:
print("Device shape:", device.shape)

print("\nActivity values:")
print(device["activity"].value_counts())

print("\nNumber of users:", device["user"].nunique())
print("Number of PCs:", device["pc"].nunique())

print("\nMissing values:")
print(device.isnull().sum())

print("\nDuplicate rows:", device.duplicated().sum())

Device shape: (65668, 5)

Activity values:
activity
Connect       34516
Disconnect    31152
Name: count, dtype: int64

Number of users: 228
Number of PCs: 228

Missing values:
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

Duplicate rows: 0

In [16]:
device["date"] = pd.to_datetime(
    device["date"],
    format="%m/%d/%Y %H:%M:%S"
)

print("Device date range:")
print(device["date"].min(), "to", device["date"].max())

Device date range:
2010-01-04 07:12:31 to 2011-05-14 05:49:30

In [17]:
http = pd.read_csv("../data/raw/r1/r1/http.csv")

print("HTTP shape:", http.shape)

print("\nColumns:")
print(http.columns.tolist())

print("\nFirst 5 rows:")
display(http.head())

HTTP shape: (3451664, 5)

Columns:
['{M8H9-W9NL75TH-1322KOLO}', '01/04/2010 07:08:47', 'DTAA/AMA0606', 'PC-1514', 'http://cnet.com']

First 5 rows:

,{M8H9-W9NL75TH-1322KOLO},01/04/2010 07:08:47,DTAA/AMA0606,PC-1514,http://cnet.com
0,{V0E1-R0FE91SC-2381GTDZ},01/04/2010 07:35:19,DTAA/DBM0698,PC-1444,http://force.open.com
1,{V7C8-H6KA39YG-3352HMOW},01/04/2010 07:40:40,DTAA/HBF0035,PC-0991,http://tendencystem.org
2,{O9P7-D9DL54YQ-9903OMYE},01/04/2010 07:52:25,DTAA/SVC0175,PC-3384,http://bent.cup.org
3,{L3J0-E4RF05KN-7341OQVW},01/04/2010 07:55:50,DTAA/CMU0028,PC-4253,http://taxpotato.east.org
4,{V8F5-V1YW04ID-3094EHZZ},01/04/2010 07:59:54,DTAA/BML0618,PC-0659,http://go.com

In [18]:
print("\nData types:")
print(http.dtypes)

print("\nMissing values:")
print(http.isnull().sum())

print("\nDuplicate rows:", http.duplicated().sum())

Data types:
{M8H9-W9NL75TH-1322KOLO}    str
01/04/2010 07:08:47         str
DTAA/AMA0606                str
PC-1514                     str
http://cnet.com             str
dtype: object

Missing values:
{M8H9-W9NL75TH-1322KOLO}    0
01/04/2010 07:08:47         0
DTAA/AMA0606                0
PC-1514                     0
http://cnet.com             0
dtype: int64

Duplicate rows: 0

In [19]:
print("HTTP columns:")
for i, col in enumerate(http.columns):
    print(i, repr(col))

HTTP columns:
0 '{M8H9-W9NL75TH-1322KOLO}'
1 '01/04/2010 07:08:47'
2 'DTAA/AMA0606'
3 'PC-1514'
4 'http://cnet.com'

In [20]:
http = pd.read_csv(
    "../data/raw/r1/r1/http.csv",
    header=None,
    names=["id", "date", "user", "pc", "url"]
)

print("HTTP shape:", http.shape)

print("\nColumns:")
print(http.columns.tolist())

print("\nFirst 5 rows:")
display(http.head())

HTTP shape: (3451665, 5)

Columns:
['id', 'date', 'user', 'pc', 'url']

First 5 rows:

,id,date,user,pc,url
0,{M8H9-W9NL75TH-1322KOLO},01/04/2010 07:08:47,DTAA/AMA0606,PC-1514,http://cnet.com
1,{V0E1-R0FE91SC-2381GTDZ},01/04/2010 07:35:19,DTAA/DBM0698,PC-1444,http://force.open.com
2,{V7C8-H6KA39YG-3352HMOW},01/04/2010 07:40:40,DTAA/HBF0035,PC-0991,http://tendencystem.org
3,{O9P7-D9DL54YQ-9903OMYE},01/04/2010 07:52:25,DTAA/SVC0175,PC-3384,http://bent.cup.org
4,{L3J0-E4RF05KN-7341OQVW},01/04/2010 07:55:50,DTAA/CMU0028,PC-4253,http://taxpotato.east.org

In [21]:
print("Missing values:")
print(http.isnull().sum())

print("\nDuplicate rows:", http.duplicated().sum())

print("\nUsers:", http["user"].nunique())
print("PCs:", http["pc"].nunique())

Missing values:
id      0
date    0
user    0
pc      0
url     0
dtype: int64

Duplicate rows: 0

Users: 1000
PCs: 1100

In [22]:
http["date"] = pd.to_datetime(
    http["date"],
    format="%m/%d/%Y %H:%M:%S"
)

print("HTTP date range:")
print(http["date"].min(), "to", http["date"].max())

HTTP date range:
2010-01-04 07:08:47 to 2011-05-14 06:10:53

In [23]:
print("Missing values:")
print(http.isnull().sum())

print("\nDuplicate rows:", http.duplicated().sum())

print("\nUsers:", http["user"].nunique())
print("PCs:", http["pc"].nunique())

Missing values:
id      0
date    0
user    0
pc      0
url     0
dtype: int64

Duplicate rows: 0

Users: 1000
PCs: 1100

In [24]:
print("Missing values:")
print(http.isnull().sum())

print("\nDuplicate rows:")
print(http.duplicated().sum())

print("\nNumber of users:", http["user"].nunique())
print("Number of PCs:", http["pc"].nunique())

Missing values:
id      0
date    0
user    0
pc      0
url     0
dtype: int64

Duplicate rows:
0

Number of users: 1000
Number of PCs: 1100

In [25]:
http["date"] = pd.to_datetime(
    http["date"],
    format="%m/%d/%Y %H:%M:%S"
)

print("HTTP date range:")
print(http["date"].min())
print("to")
print(http["date"].max())

HTTP date range:
2010-01-04 07:08:47
to
2011-05-14 06:10:53

In [26]:
print("Missing values:")
print(http.isnull().sum())

print("\nDuplicate rows:")
print(http.duplicated().sum())

print("\nNumber of users:", http["user"].nunique())
print("Number of PCs:", http["pc"].nunique())

Missing values:
id      0
date    0
user    0
pc      0
url     0
dtype: int64

Duplicate rows:
0

Number of users: 1000
Number of PCs: 1100

In [ ]:
print("Missing values:")
print(http.isnull().sum())

print("\nDuplicate rows:")
print(http.duplicated().sum())

print("\nNumber of users:", http["user"].nunique())
print("Number of PCs:", http["pc"].nunique())

Missing values:
id      0
date    0
user    0
pc      0
url     0
dtype: int64

Duplicate rows:
0

Number of users: 1000
Number of PCs: 1100